In [14]:
import pandas as pd
import numpy as np

In [19]:
import os
os.getcwd()

'C:\\Users\\hp\\Data Analysis\\EDA\\Pandas\\Lessons'

In [24]:
df = pd.read_csv("Data\std_data1.csv")
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [25]:
pd.read_csv(r"Data\std_data1.csv",index_col = "SNAME")

       SCLASS   ENGLISH  COMPUTER  SCIENCE
SNAME
A           10       67        66       66
B           12       87        56       65
C           11       66        89       63
D           10       56        88       66
E           10       89        90       56
F            9       88        85       89
G           12       90        83       88
H           11       79        88       90

In [27]:
df_index = df.set_index("SNAME")
df_index

       SCLASS   ENGLISH  COMPUTER  SCIENCE
SNAME
A           10       67        66       66
B           12       87        56       65
C           11       66        89       63
D           10       56        88       66
E           10       89        90       56
F            9       88        85       89
G           12       90        83       88
H           11       79        88       90

In [29]:
df_index1 = df.set_index("SNAME",drop = False)
df_index1

      SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
SNAME
A         A       10       67        66       66
B         B       12       87        56       65
C         C       11       66        89       63
D         D       10       56        88       66
E         E       10       89        90       56
F         F        9       88        85       89
G         G       12       90        83       88
H         H       11       79        88       90

In [30]:
df_index1.reset_index(drop = True)

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

# Sorting DataFrame

In [31]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [33]:
df.iloc[[2,5,3,7,1],:]

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
2     C       11       66        89       63
5     F        9       88        85       89
3     D       10       56        88       66
7     H       11       79        88       90
1     B       12       87        56       65

In [35]:
df.iloc[[2,5,3,7,1],:].sort_index() #sorting by index

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
5     F        9       88        85       89
7     H       11       79        88       90

In [43]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [44]:
df.sort_index(ascending = False) #in descending order by index

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
7     H       11       79        88       90
6     G       12       90        83       88
5     F        9       88        85       89
4     E       10       89        90       56
3     D       10       56        88       66
2     C       11       66        89       63
1     B       12       87        56       65
0     A       10       67        66       66

# Sorting DataFrame by values

In [39]:
df.sort_values(by = "ENGLISH")

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
3     D       10       56        88       66
2     C       11       66        89       63
0     A       10       67        66       66
7     H       11       79        88       90
1     B       12       87        56       65
5     F        9       88        85       89
4     E       10       89        90       56
6     G       12       90        83       88

In [42]:
df.sort_values(by = "ENGLISH", ascending = False) #inndescendong order

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
6     G       12       90        83       88
4     E       10       89        90       56
5     F        9       88        85       89
1     B       12       87        56       65
7     H       11       79        88       90
0     A       10       67        66       66
2     C       11       66        89       63
3     D       10       56        88       66

In [46]:
df.sort_values(by = ["ENGLISH","SNAME","COMPUTER","SCIENCE"])

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
3     D       10       56        88       66
2     C       11       66        89       63
0     A       10       67        66       66
7     H       11       79        88       90
1     B       12       87        56       65
5     F        9       88        85       89
4     E       10       89        90       56
6     G       12       90        83       88

In [47]:
df.sort_values(by = ["ENGLISH","SNAME","COMPUTER","SCIENCE"],ascending = False)

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
6     G       12       90        83       88
4     E       10       89        90       56
5     F        9       88        85       89
1     B       12       87        56       65
7     H       11       79        88       90
0     A       10       67        66       66
2     C       11       66        89       63
3     D       10       56        88       66