In [46]:
import pandas as pd

dict1={ 
       "City":["Simla","Delhi","Jaipur","Bhopal"],
       "Temp":[15,33,38,35]
}

dict2={ 
       "City":["Chennai","Hyderabad","Vizag","Kochi"],
       "Humid":[39,34,36,30]
}

dfnorth=pd.DataFrame(dict1)
dfsouth=pd.DataFrame(dict2)

In [47]:
display(dfnorth,dfsouth)

     City  Temp
0   Simla    15
1   Delhi    33
2  Jaipur    38
3  Bhopal    35

        City  Humid
0    Chennai     39
1  Hyderabad     34
2      Vizag     36
3      Kochi     30

In [48]:
pd.concat([dfnorth,dfsouth])

        City  Temp  Humid
0      Simla  15.0    NaN
1      Delhi  33.0    NaN
2     Jaipur  38.0    NaN
3     Bhopal  35.0    NaN
0    Chennai   NaN   39.0
1  Hyderabad   NaN   34.0
2      Vizag   NaN   36.0
3      Kochi   NaN   30.0

In [49]:
pd.concat([dfnorth,dfsouth],ignore_index=True)

        City  Temp  Humid
0      Simla  15.0    NaN
1      Delhi  33.0    NaN
2     Jaipur  38.0    NaN
3     Bhopal  35.0    NaN
4    Chennai   NaN   39.0
5  Hyderabad   NaN   34.0
6      Vizag   NaN   36.0
7      Kochi   NaN   30.0

In [50]:
df_key=pd.concat([dfnorth,dfsouth],keys=["North","South"])
df_key

              City  Temp  Humid
North 0      Simla  15.0    NaN
      1      Delhi  33.0    NaN
      2     Jaipur  38.0    NaN
      3     Bhopal  35.0    NaN
South 0    Chennai   NaN   39.0
      1  Hyderabad   NaN   34.0
      2      Vizag   NaN   36.0
      3      Kochi   NaN   30.0

In [51]:
df_key.loc["North"]

     City  Temp  Humid
0   Simla  15.0    NaN
1   Delhi  33.0    NaN
2  Jaipur  38.0    NaN
3  Bhopal  35.0    NaN

In [52]:
df_key.loc["North"]["Temp"]

0    15.0
1    33.0
2    38.0
3    35.0
Name: Temp, dtype: float64

In [63]:
dict3={ 
       "City":["Simla","Delhi","Jaipur","Bhopal"],
       "Temp":[15,33,38,35]
}

dict4={ 
       "City":["Chennai","Hyderabad","Vizag","Kochi"],
       "Humid":[39,34,36,30]
}

dftemp=pd.DataFrame(dict3)
dfhumid=pd.DataFrame(dict4)

In [64]:
display(dftemp,dfhumid)

     City  Temp
0   Simla    15
1   Delhi    33
2  Jaipur    38
3  Bhopal    35

        City  Humid
0    Chennai     39
1  Hyderabad     34
2      Vizag     36
3      Kochi     30

In [65]:
pd.concat([dfnorth,dfsouth],axis=1)

     City  Temp       City  Humid
0   Simla    15    Chennai     39
1   Delhi    33  Hyderabad     34
2  Jaipur    38      Vizag     36
3  Bhopal    35      Kochi     30

# Joins

In [96]:
dict5={ 
       "City":["Chennai","Hyderabad","Vizag","Kochi","Mumbai"],
       "State":["TN","TS","AP","KS","MH"],
       "Temp":[15,33,38,35,30]
}

dict6={ 
       "City":["Chennai","Hyderabad","Vizag","Kochi","Pune"],
       "State":["TN","TS","AP","KS","MH"],
       "Humid":[39,34,36,30,39]
}

dftemp=pd.DataFrame(dict5)
dfhumid=pd.DataFrame(dict6)

In [97]:
display(dftemp,dfhumid)

        City State  Temp
0    Chennai    TN    15
1  Hyderabad    TS    33
2      Vizag    AP    38
3      Kochi    KS    35
4     Mumbai    MH    30

        City State  Humid
0    Chennai    TN     39
1  Hyderabad    TS     34
2      Vizag    AP     36
3      Kochi    KS     30
4       Pune    MH     39

In [98]:
pd.merge(dftemp,dfhumid)

        City State  Temp  Humid
0    Chennai    TN    15     39
1  Hyderabad    TS    33     34
2      Vizag    AP    38     36
3      Kochi    KS    35     30

In [99]:
pd.merge(dftemp,dfhumid, on ="City")

        City State_x  Temp State_y  Humid
0    Chennai      TN    15      TN     39
1  Hyderabad      TS    33      TS     34
2      Vizag      AP    38      AP     36
3      Kochi      KS    35      KS     30

In [100]:
display(dftemp,dfhumid)

        City State  Temp
0    Chennai    TN    15
1  Hyderabad    TS    33
2      Vizag    AP    38
3      Kochi    KS    35
4     Mumbai    MH    30

        City State  Humid
0    Chennai    TN     39
1  Hyderabad    TS     34
2      Vizag    AP     36
3      Kochi    KS     30
4       Pune    MH     39

In [101]:
pd.merge(dftemp,dfhumid, how ="inner")

        City State  Temp  Humid
0    Chennai    TN    15     39
1  Hyderabad    TS    33     34
2      Vizag    AP    38     36
3      Kochi    KS    35     30

In [102]:
pd.merge(dftemp,dfhumid, how ="left")

        City State  Temp  Humid
0    Chennai    TN    15   39.0
1  Hyderabad    TS    33   34.0
2      Vizag    AP    38   36.0
3      Kochi    KS    35   30.0
4     Mumbai    MH    30    NaN

In [103]:
pd.merge(dftemp,dfhumid, how ="right")

        City State  Temp  Humid
0    Chennai    TN  15.0     39
1  Hyderabad    TS  33.0     34
2      Vizag    AP  38.0     36
3      Kochi    KS  35.0     30
4       Pune    MH   NaN     39

In [104]:
pd.merge(dftemp,dfhumid, how ="outer")

        City State  Temp  Humid
0    Chennai    TN  15.0   39.0
1  Hyderabad    TS  33.0   34.0
2      Kochi    KS  35.0   30.0
3     Mumbai    MH  30.0    NaN
4       Pune    MH   NaN   39.0
5      Vizag    AP  38.0   36.0

In [105]:
pd.merge(dftemp,dfhumid, how ="cross")

       City_x State_x  Temp     City_y State_y  Humid
0     Chennai      TN    15    Chennai      TN     39
1     Chennai      TN    15  Hyderabad      TS     34
2     Chennai      TN    15      Vizag      AP     36
3     Chennai      TN    15      Kochi      KS     30
4     Chennai      TN    15       Pune      MH     39
5   Hyderabad      TS    33    Chennai      TN     39
6   Hyderabad      TS    33  Hyderabad      TS     34
7   Hyderabad      TS    33      Vizag      AP     36
8   Hyderabad      TS    33      Kochi      KS     30
9   Hyderabad      TS    33       Pune      MH     39
10      Vizag      AP    38    Chennai      TN     39
11      Vizag      AP    38  Hyderabad      TS     34
12      Vizag      AP    38      Vizag      AP     36
13      Vizag      AP    38      Kochi      KS     30
14      Vizag      AP    38       Pune      MH     39
15      Kochi      KS    35    Chennai      TN     39
16      Kochi      KS    35  Hyderabad      TS     34
17      Kochi      KS    35      Vizag      AP     36
18      Kochi      KS    35      Kochi      KS     30
19      Kochi      KS    35       Pune      MH     39
20     Mumbai      MH    30    Chennai      TN     39
21     Mumbai      MH    30  Hyderabad      TS     34
22     Mumbai      MH    30      Vizag      AP     36
23     Mumbai      MH    30      Kochi      KS     30
24     Mumbai      MH    30       Pune      MH     39

In [125]:
dict7={ 
       "City":["Simla","Delhi","Jaipur","Bhopal"],
       "Temp":[15,33,38,35]
}

dict8={ 
       "City":["Chennai","Hyderabad","Vizag","Kochi"],
       "Humid":[39,34,36,30]
}

df1=pd.DataFrame(dict7)
df2=pd.DataFrame(dict8)

In [126]:
display(df1,df2)

     City  Temp
0   Simla    15
1   Delhi    33
2  Jaipur    38
3  Bhopal    35

        City  Humid
0    Chennai     39
1  Hyderabad     34
2      Vizag     36
3      Kochi     30

In [138]:
df1.join(df2,rsuffix="_R")

     City  Temp     City_R  Humid
0   Simla    15    Chennai     39
1   Delhi    33  Hyderabad     34
2  Jaipur    38      Vizag     36
3  Bhopal    35      Kochi     30

In [139]:
df1.join(df2,lsuffix="_L")

   City_L  Temp       City  Humid
0   Simla    15    Chennai     39
1   Delhi    33  Hyderabad     34
2  Jaipur    38      Vizag     36
3  Bhopal    35      Kochi     30

In [140]:
pd.concat([df1,dfsouth],axis=1)

     City  Temp       City  Humid
0   Simla    15    Chennai     39
1   Delhi    33  Hyderabad     34
2  Jaipur    38      Vizag     36
3  Bhopal    35      Kochi     30

In [141]:
pd.concat([df1,df2],axis=0)

        City  Temp  Humid
0      Simla  15.0    NaN
1      Delhi  33.0    NaN
2     Jaipur  38.0    NaN
3     Bhopal  35.0    NaN
0    Chennai   NaN   39.0
1  Hyderabad   NaN   34.0
2      Vizag   NaN   36.0
3      Kochi   NaN   30.0