# Data types in Pandas

In [1]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [3]:
#creating Data Frame
data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Service": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df = pd.DataFrame(data)
df.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [4]:
df.dtypes

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

# Converting the data types of columns

In [5]:
df["Year"].astype("int")

0    1990
1    1980
2    2003
3    2000
4    2001
5    2004
6    1999
7    2020
Name: Year, dtype: int64

In [9]:
df["Year"] = df["Year"].astype("int")

In [10]:
df.dtypes

Car        object
Color      object
Year        int64
Rating     object
Service    object
dtype: object

In [11]:
df["Rating"] = df["Rating"].astype("float")

In [12]:
df.dtypes

Car         object
Color       object
Year         int64
Rating     float64
Service     object
dtype: object

In [14]:
df.dtypes

Car         object
Color       object
Year         int64
Rating     float64
Service     object
dtype: object

In [22]:
data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Service": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df1 = pd.DataFrame(data)
df1

       Car   Color  Year Rating     Service
0      BMW     Red  1990    2.5  30/04/2023
1     ALTO  Yellow  1980    1.5  31/08/1999
2     AUDI   Black  2003    3.8  28/12/2015
3   MARUTI   Green  2000    9.7  29/06/2011
4    HONDA   Black  2001    8.9  30/12/2020
5  HYUNDAI     Red  2004    3.2  31/07/2013
6     FORD   Black  1999    5.5  28/11/2000
7      KIA   Black  2020    6.9  25/12/2020

In [23]:
df1.dtypes

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

In [24]:
#using pd.to_numeric
df1["Year"] = pd.to_numeric(df1["Year"])

In [25]:
df1.dtypes

Car        object
Color      object
Year        int64
Rating     object
Service    object
dtype: object

In [26]:
df1["Rating"] = pd.to_numeric(df1["Rating"])

In [27]:
df1.dtypes

Car         object
Color       object
Year         int64
Rating     float64
Service     object
dtype: object

In [29]:
df1["Service"] = pd.to_datetime(df1["Service"])

In [30]:
df1.dtypes

Car                object
Color              object
Year                int64
Rating            float64
Service    datetime64[ns]
dtype: object

In [31]:
df2 = pd.DataFrame(data)
df2.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [33]:
df2["Year"] = df2["Year"].astype("int")
df2["Year"]

0    1990
1    1980
2    2003
3    2000
4    2001
5    2004
6    1999
7    2020
Name: Year, dtype: int64

In [34]:
df2["Year"].astype("int")

0    1990
1    1980
2    2003
3    2000
4    2001
5    2004
6    1999
7    2020
Name: Year, dtype: int64

In [35]:
df2 = df2.astype({"Year":"int","Rating":"float","Service":"datetime64[ns]"})

In [36]:
df2.dtypes

Car                object
Color              object
Year                int64
Rating            float64
Service    datetime64[ns]
dtype: object

In [37]:
df3 = pd.DataFrame(data)
df3.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [38]:
df3.dtypes

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

In [39]:
# Not reccomendable
df3 = df3.convert_dtypes()

In [40]:
df3.dtypes

Car        string[python]
Color      string[python]
Year       string[python]
Rating     string[python]
Service    string[python]
dtype: object