In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv(r"data\loandata.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y
613,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,N

In [4]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y

# groupby

In [10]:
 #mean
df.groupby(by = "Gender").mean(numeric_only = True)

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
Gender,,,,,
Female,4643.473214,1108.008929,126.697248,352.293578,0.831683
Male,5446.460123,1742.932352,149.265957,339.665272,0.847007

In [9]:
#for specific column
df.groupby(by = "Gender")["ApplicantIncome"].mean(numeric_only = True)

Gender
Female    4643.473214
Male      5446.460123
Name: ApplicantIncome, dtype: float64

In [11]:
df.Education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [12]:
df.Education.value_counts()

Education
Graduate        480
Not Graduate    134
Name: count, dtype: int64

In [13]:
df.groupby(by = "Education")["ApplicantIncome"].mean()

Education
Graduate        5857.433333
Not Graduate    3777.283582
Name: ApplicantIncome, dtype: float64

In [15]:
#multiple columns
df.groupby(by = "Education")[["ApplicantIncome","LoanAmount"]].mean()

              ApplicantIncome  LoanAmount
Education
Graduate          5857.433333  154.060215
Not Graduate      3777.283582  118.409449

# Using multiple columns for groupby

In [16]:
df.groupby(by = ["Married","Gender"])[["ApplicantIncome","LoanAmount"]].mean()

                ApplicantIncome  LoanAmount
Married Gender
No      Female      4503.787500  116.115385
        Male        5236.146154  136.088000
Yes     Female      4829.645161  153.322581
        Male        5529.540616  154.011662

In [17]:
df.groupby(by = ["Married","Gender"]).mean(numeric_only = True)

                ApplicantIncome  CoapplicantIncome  LoanAmount  \
Married Gender
No      Female      4503.787500        1020.012500  116.115385
        Male        5236.146154        1529.430769  136.088000
Yes     Female      4829.645161        1370.838710  153.322581
        Male        5529.540616        1828.330308  154.011662

                Loan_Amount_Term  Credit_History
Married Gender
No      Female        355.012987        0.821918
        Male          348.562500        0.845528
Yes     Female        349.161290        0.851852
        Male          335.931034        0.846626

In [20]:
# max value by grouoing
df.groupby(by = ["Married"])[["ApplicantIncome"]].max()

         ApplicantIncome
Married
No                 37719
Yes                81000

# Aggregation Function on Groupby

In [21]:
df.groupby(by = ["Gender","Married"])["Gender"].agg("count")

Gender  Married
Female  No          80
        Yes         31
Male    No         130
        Yes        357
Name: Gender, dtype: int64

In [22]:
#multiple agg functions
df.groupby(by = "Married")["LoanAmount"].agg([np.mean,np.std,np.min,np.max])

               mean        std   min    max
Married
No       128.883495  74.385981   9.0  650.0
Yes      155.750000  89.934267  17.0  700.0

In [23]:
# groupby gives datstricture dataframegroupby
df1 = df.groupby(by = ["Married","Gender"])

In [24]:
df1

In [26]:
type(df1)

pandas.core.groupby.generic.DataFrameGroupBy

In [27]:
df1["ApplicantIncome"].mean().sort_values()

Married  Gender
No       Female    4503.787500
Yes      Female    4829.645161
No       Male      5236.146154
Yes      Male      5529.540616
Name: ApplicantIncome, dtype: float64

# Crosstab

In [28]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y

In [29]:
pd.crosstab(df["Gender"], df["Married"])

Married   No  Yes
Gender
Female    80   31
Male     130  357

In [31]:
df.groupby(by = ["Gender","Married"])["Gender"].count() #same but we choose what to use

Gender  Married
Female  No          80
        Yes         31
Male    No         130
        Yes        357
Name: Gender, dtype: int64

# Compare Average Income wit rspect to Gender and Married

In [32]:
##using crosstab
pd.crosstab(df["Gender"], df["Married"], values = df["ApplicantIncome"], aggfunc = "mean")

Married           No          Yes
Gender
Female   4503.787500  4829.645161
Male     5236.146154  5529.540616

In [33]:
##using groupby
df.groupby(by =["Married","Gender"])["ApplicantIncome"].mean()

Married  Gender
No       Female    4503.787500
         Male      5236.146154
Yes      Female    4829.645161
         Male      5529.540616
Name: ApplicantIncome, dtype: float64

# Pivot Table

In [34]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y
613,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,N

In [35]:
#Pivot table on ApplicantIncome mean value based on gender
df.pivot_table(values = "ApplicantIncome", index = "Gender", aggfunc = "mean")

        ApplicantIncome
Gender
Female      4643.473214
Male        5446.460123

In [37]:
# Pivot table on ApplicantINcome mean value based  on fender and married column
df.pivot_table(values = "ApplicantIncome", index = "Gender",columns = "Married",aggfunc = "mean")

Married           No          Yes
Gender
Female   4503.787500  4829.645161
Male     5236.146154  5529.540616

In [38]:
# Pivot table on ApplicantINcome count value based  on fender and married column
df.pivot_table(values = "ApplicantIncome", index = "Gender",columns = "Married",aggfunc = "count")

Married   No  Yes
Gender
Female    80   31
Male     130  357

In [39]:
#ussing crosstab
pd.crosstab(df["Gender"], df["Married"], values = df["ApplicantIncome"], aggfunc = "mean")

Married           No          Yes
Gender
Female   4503.787500  4829.645161
Male     5236.146154  5529.540616

In [43]:
#ussing gruopby
df.groupby(by =["Gender","Married"])[["ApplicantIncome"]].count()

                ApplicantIncome
Gender Married
Female No                    80
       Yes                   31
Male   No                   130
       Yes                  357

In [44]:
pd.crosstab(df["Property_Area"],df["Loan_Status"])

Loan_Status     N    Y
Property_Area
Rural          69  110
Semiurban      54  179
Urban          69  133

In [55]:
df.groupby(by = ["Loan_Status"])[["ApplicantIncome","CoapplicantIncome"]].mean(numeric_only = True)

             ApplicantIncome  CoapplicantIncome
Loan_Status
N                5446.078125        1877.807292
Y                5384.068720        1504.516398

In [52]:
df.pivot_table(values = "LoanAmount" ,index = "Education", aggfunc = "mean")

              LoanAmount
Education
Graduate      154.060215
Not Graduate  118.409449

In [56]:
pd.crosstab(df["Self_Employed"],df["Loan_Status"])

Loan_Status      N    Y
Self_Employed
No             157  343
Yes             26   56

In [5]:
pd.crosstab(df["Self_Employed"],df["Loan_Status"])

Loan_Status      N    Y
Self_Employed
No             157  343
Yes             26   56

In [9]:
df.groupby(by = "Self_Employed")[["ApplicantIncome"]].count()

               ApplicantIncome
Self_Employed
No                         500
Yes                         82

In [10]:
df.pivot_table(values = "Self_Employed", index = "Gender", aggfunc = "count")

        Self_Employed
Gender
Female            104
Male              465