# Missing Values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Data\std_multinan.csv")
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [6]:
df.isnull() #gives true where missing value occurs

    Name  English  Science
0  False    False     False
1  False     True     False
2  False     True     False
3  False     True     False
4  False     True     False
5   True    False      True
6  False    False      True
7   True    False      True
8  False    False     False

In [8]:
df.notnull() #opposite to above

    Name  English  Science
0   True     True      True
1   True    False      True
2   True    False      True
3   True    False      True
4   True    False      True
5  False     True     False
6   True     True     False
7  False     True     False
8   True     True      True

In [10]:
df.isna() #same as isnull

    Name  English  Science
0  False    False     False
1  False     True     False
2  False     True     False
3  False     True     False
4  False     True     False
5   True    False      True
6  False    False      True
7   True    False      True
8  False    False     False

In [11]:
df.notna()

    Name  English  Science
0   True     True      True
1   True    False      True
2   True    False      True
3   True    False      True
4   True    False      True
5  False     True     False
6   True     True     False
7  False     True     False
8   True     True      True

In [13]:
df.isnull().values.any() #return if any value in DataFrame as NaN

np.True_

In [17]:
df.isnull().sum() #how amny nan values

Name        2
English     4
Science     3
dtype: int64

In [18]:
df.notnull().sum() #opposiote above

Name        7
English     5
Science     6
dtype: int64

# Handling Missing Values

In [19]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [21]:
df.dropna() #drop missing value rows

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

# Parameters in dropna that we can use

* axis
* how
* thresh
* subset
* inplace

In [22]:
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

# thresh

In [28]:
df.dropna(axis = 1, thresh = 7)

  Name
0  AAA
1  BBB
2  CCC
3  DDD
4  EEE
5  NaN
6  GGG
7  NaN
8  KKK

In [26]:
df.dropna(axis = 1, thresh = 7).count()

Name    7
dtype: int64

In [27]:
df.dropna()

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

# how

In [29]:
df.dropna(how = "any")

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

In [30]:
df.dropna(how = "all")

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

# subset

In [31]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [32]:
df.dropna(subset = ["Name", "English"])

  Name  English  Science
0  AAA     50.0      40.0
6  GGG     45.0       NaN
8  KKK     90.0      90.0

In [35]:
df.dropna(subset = ["Name", "Science "])

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
8  KKK     90.0      90.0

# inplace

In [44]:
df #iot is not permenant

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [45]:
df.dropna(inplace = True) #it makes permanant

In [42]:
df

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

# drop

In [48]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [51]:
df.drop("English", axis = 1) #drop enlish column

  Name  Science
0  AAA      40.0
1  BBB      45.0
2  CCC      58.0
3  DDD      90.0
4  EEE      55.0
5  NaN       NaN
6  GGG       NaN
7  NaN       NaN
8  KKK      90.0

In [53]:
df.drop(1) #drop first index row

  Name  English  Science
0  AAA     50.0      40.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

# droping multiple column

In [55]:
df.drop(["English", "Science "], axis = 1) #drop mentioned columns

  Name
0  AAA
1  BBB
2  CCC
3  DDD
4  EEE
5  NaN
6  GGG
7  NaN
8  KKK

In [60]:
df.drop(columns = ["English", "Science "]) #same as above without mentioning axis

  Name
0  AAA
1  BBB
2  CCC
3  DDD
4  EEE
5  NaN
6  GGG
7  NaN
8  KKK

# Filling Missing Values

In [3]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [5]:
df.fillna(0, axis = 1) #fill 0 where nan values present

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\3518361257.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0, axis = 1) #fill 0 where nan values present

  Name English Science
0  AAA    50.0     40.0
1  BBB       0     45.0
2  CCC       0     58.0
3  DDD       0     90.0
4  EEE       0     55.0
5  0.0    40.0      0.0
6  GGG    45.0        0
7  0.0    58.0      0.0
8  KKK    90.0     90.0

# Backward fill

In [6]:
df.fillna(method = "bfill")

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

  Name  English  Science
0  AAA     50.0      40.0
1  BBB     50.0      45.0
2  CCC     50.0      58.0
3  DDD     50.0      90.0
4  EEE     50.0      55.0
5  EEE     40.0      55.0
6  GGG     45.0      55.0
7  GGG     58.0      55.0
8  KKK     90.0      90.0

# Forward fill

In [7]:
df.fillna(method = "ffill")

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

  Name  English  Science
0  AAA     50.0      40.0
1  BBB     50.0      45.0
2  CCC     50.0      58.0
3  DDD     50.0      90.0
4  EEE     50.0      55.0
5  EEE     40.0      55.0
6  GGG     45.0      55.0
7  GGG     58.0      55.0
8  KKK     90.0      90.0

# Mean

In [8]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [9]:
df.dtypes

Name         object
English     float64
Science     float64
dtype: object

In [10]:
df["English"].fillna(df["English"].mean())

0    50.0
1    56.6
2    56.6
3    56.6
4    56.6
5    40.0
6    45.0
7    58.0
8    90.0
Name: English, dtype: float64

In [11]:
df["Science "].fillna(df["Science "].mean())

0    40.0
1    45.0
2    58.0
3    90.0
4    55.0
5    63.0
6    63.0
7    63.0
8    90.0
Name: Science , dtype: float64

# Median

In [12]:
df["English"].fillna(df["English"].median())

0    50.0
1    50.0
2    50.0
3    50.0
4    50.0
5    40.0
6    45.0
7    58.0
8    90.0
Name: English, dtype: float64

In [13]:
df["Science "].fillna(df["Science "].median())

0    40.0
1    45.0
2    58.0
3    90.0
4    55.0
5    56.5
6    56.5
7    56.5
8    90.0
Name: Science , dtype: float64

# Mode

In [18]:
df1 = pd.read_csv("data\std_dropna.csv")
df1

   StdID StdName  Class Location  Total  Unnamed: 5
0  111.0       A   10.0      NaN  180.0         NaN
1    NaN       B   11.0      Viz    NaN         NaN
2  113.0     NaN   12.0      Blr  150.0         NaN
3    NaN     NaN    NaN      NaN    NaN         NaN
4  115.0       E   10.0      Viz    NaN         NaN
5    NaN       F   11.0      Blr  140.0         NaN
6  117.0       G    NaN      Hyd  188.0         NaN
7    NaN     NaN    NaN      NaN    NaN         NaN
8  119.0       I    9.0      Blr    NaN         NaN
9    NaN     NaN    NaN      NaN    NaN         NaN

In [16]:
df1.dtypes

StdID         float64
StdName        object
Class         float64
Location       object
Total         float64
Unnamed: 5    float64
dtype: object

In [17]:
df.columns

Index(['Name', 'English', 'Science '], dtype='object')

In [20]:
df1["Location"].mode()

0    Blr
Name: Location, dtype: object

In [19]:
df1["Location"].mode()[0]

'Blr'

In [21]:
df1["Location"].fillna(df1["Location"].mode()[0])

0    Blr
1    Viz
2    Blr
3    Blr
4    Viz
5    Blr
6    Hyd
7    Blr
8    Blr
9    Blr
Name: Location, dtype: object

# (to make it permanent)since above any operation not affect dataset use inplace = True

In [22]:
df1["Location"].fillna(df1["Location"].mode()[0], inplace = True)

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\1498318891.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Location"].fillna(df1["Location"].mode()[0], inplace = True)

In [23]:
df1

   StdID StdName  Class Location  Total  Unnamed: 5
0  111.0       A   10.0      Blr  180.0         NaN
1    NaN       B   11.0      Viz    NaN         NaN
2  113.0     NaN   12.0      Blr  150.0         NaN
3    NaN     NaN    NaN      Blr    NaN         NaN
4  115.0       E   10.0      Viz    NaN         NaN
5    NaN       F   11.0      Blr  140.0         NaN
6  117.0       G    NaN      Hyd  188.0         NaN
7    NaN     NaN    NaN      Blr    NaN         NaN
8  119.0       I    9.0      Blr    NaN         NaN
9    NaN     NaN    NaN      Blr    NaN         NaN

# Interpolate function

In [26]:
dftemp = pd.read_csv("Data\hyd_outliers.csv")
dftemp

          Date    Temp
0   21-01-2022    30.0
1   22-01-2022    28.0
2   23-01-2022     NaN
3   24-01-2022    29.0
4   25-01-2022  4450.0
5   26-01-2022    32.0
6   27-01-2022    34.0
7   28-01-2022   -50.0
8   29-01-2022    36.0
9   30-01-2022    38.0
10  31-01-2022     NaN
11  13-02-2022    25.0
12  14-02-2022  1111.0
13  15-02-2022    22.0
14  16-02-2022    21.0
15  17-02-2022  9999.0
16  18-02-2022    22.0
17  19-02-2022     NaN
18  20-02-2022    20.0

In [27]:
dftemp.interpolate()

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\3140476889.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  dftemp.interpolate()

          Date    Temp
0   21-01-2022    30.0
1   22-01-2022    28.0
2   23-01-2022    28.5
3   24-01-2022    29.0
4   25-01-2022  4450.0
5   26-01-2022    32.0
6   27-01-2022    34.0
7   28-01-2022   -50.0
8   29-01-2022    36.0
9   30-01-2022    38.0
10  31-01-2022    31.5
11  13-02-2022    25.0
12  14-02-2022  1111.0
13  15-02-2022    22.0
14  16-02-2022    21.0
15  17-02-2022  9999.0
16  18-02-2022    22.0
17  19-02-2022    21.0
18  20-02-2022    20.0

In [30]:
dfage = pd.read_csv("Data\std_interp.csv")
dfage

  Stdname  StdClass   Age
0     AAA        10  15.0
1     BBB        11   NaN
2     CCC        12  18.0
3     DDD        10   NaN
4     EEE        11  16.0
5     FFF        12  18.0
6     GGG        11  16.0
7     HHH        10  15.0
8     JJJ        12   NaN
9     KKK        10   NaN

In [31]:
dfage.interpolate()

C:\Users\hp\AppData\Local\Temp\ipykernel_8424\1820636477.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  dfage.interpolate()

  Stdname  StdClass   Age
0     AAA        10  15.0
1     BBB        11  16.5
2     CCC        12  18.0
3     DDD        10  17.0
4     EEE        11  16.0
5     FFF        12  18.0
6     GGG        11  16.0
7     HHH        10  15.0
8     JJJ        12  15.0
9     KKK        10  15.0