# PANDAS Series

In [1]:
import pandas as pd
import numpy as np

In [3]:
#creating series using 1D array
arr = np.arange(10,51,10)
print(arr, type(arr))
print()
s = pd.Series(arr)
print(s, type(s))

[10 20 30 40 50] <class 'numpy.ndarray'>

0    10
1    20
2    30
3    40
4    50
dtype: int64 <class 'pandas.core.series.Series'>

In [4]:
# creating a series with mutable index
s = pd.Series(arr,index = ["first","second","third","fourth","fifth"])
print(s, type(s))

first     10
second    20
third     30
fourth    40
fifth     50
dtype: int64 <class 'pandas.core.series.Series'>

In [5]:
#Creating series using list of elements
s = pd.Series([11,22,33,44,55])
print(s, type(s))

0    11
1    22
2    33
3    44
4    55
dtype: int64 <class 'pandas.core.series.Series'>

In [6]:
#Creating a series using scalar values
s = pd.Series(99, index = [1,2,3,4,5])
print(s, type(s))

1    99
2    99
3    99
4    99
5    99
dtype: int64 <class 'pandas.core.series.Series'>

In [8]:
s = pd.Series(99, index = list(range(1001)))
print(s, type(s))

0       99
1       99
2       99
3       99
4       99
        ..
996     99
997     99
998     99
999     99
1000    99
Length: 1001, dtype: int64 <class 'pandas.core.series.Series'>

In [9]:
s = pd.Series(np.nan, index = list(range(5)))
print(s, type(s))

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64 <class 'pandas.core.series.Series'>

In [10]:
s = pd.Series(np.inf, index = list(range(5)))
print(s, type(s))

0    inf
1    inf
2    inf
3    inf
4    inf
dtype: float64 <class 'pandas.core.series.Series'>

In [11]:
#Creating a Series using python dictionary
d = {"name":"MS DHONI","Team":"CSK","Role":"Captain","Jersey number":7}
s = pd.Series(d)
print(s, type(s))

name             MS DHONI
Team                  CSK
Role              Captain
Jersey number           7
dtype: object <class 'pandas.core.series.Series'>

# PANDAS Data Frame

In [12]:
#creating datafram
#empty
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [14]:
#converting a pandas series in dataframe
df = pd.DataFrame(s)
print(df)

                      0
name           MS DHONI
Team                CSK
Role            Captain
Jersey number         7

In [15]:
#Creating Dataframe from 2D array
arr = np.arange(10,101,10).reshape(5,2)
print(arr)
df=pd.DataFrame(arr)
print(df)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
    0    1
0  10   20
1  30   40
2  50   60
3  70   80
4  90  100

In [16]:
df

    0    1
0  10   20
1  30   40
2  50   60
3  70   80
4  90  100

In [17]:
#naming the coloumns
arr = np.arange(10,101,10).reshape(5,2)
print(arr)
df=pd.DataFrame(arr, columns = ["col1","col2"])
print(df)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
   col1  col2
0    10    20
1    30    40
2    50    60
3    70    80
4    90   100

In [18]:
df

   col1  col2
0    10    20
1    30    40
2    50    60
3    70    80
4    90   100

In [20]:
# creating data frame from list dictionaries.
d = [{"name":"Rohit Sharma","team":"MI"} , {"name":"Virat Kohali","team":"RCB"}, {"name":"Hardik Pandya","team":"MI"}]
df = pd.DataFrame(d)
df

            name team
0   Rohit Sharma   MI
1   Virat Kohali  RCB
2  Hardik Pandya   MI

In [22]:
# creating data frame from list of list
d = [["Rohit Sharma","MI"] , ["Virat Kohali","RCB"], ["Hardik Pandya","MI"]]
df = pd.DataFrame(d, columns = ["name","team"])
df

            name team
0   Rohit Sharma   MI
1   Virat Kohali  RCB
2  Hardik Pandya   MI

# Activity
## Create a dataframe for 10 students with phy,chem and math score

In [28]:
d = [["Rohit",90,66,78] , ["Virat",45,66,99], ["Hardik",35,66,76] ,["Ashwin",55,66,77],["Kunal",34,56,76],["Yash",35,77,76],["Ritesh",45,76,86],["Saurabh",55,66,76],["Prasad",85,96,99],["Raj",35,66,86]]
df = pd.DataFrame(d, columns = ["Name","Physics","Chemistry","Mathematics"])
df

      Name  Physics  Chemistry  Mathematics
0    Rohit       90         66           78
1    Virat       45         66           99
2   Hardik       35         66           76
3   Ashwin       55         66           77
4    Kunal       34         56           76
5     Yash       35         77           76
6   Ritesh       45         76           86
7  Saurabh       55         66           76
8   Prasad       85         96           99
9      Raj       35         66           86

In [2]:
d = {
    "Name": [ "a","b","c","d","e","f","g","h","i","r"],
    "Physics" : [70,77,88,99,66,55,77,99,33,88],
    "Chemistry" : [70,77,88,99,66,55,77,99,33,88],
    "Mathematics" : [70,77,88,99,66,55,77,99,33,88]
}
df = pd.DataFrame(d)
df

  Name  Physics  Chemistry  Mathematics
0    a       70         70           70
1    b       77         77           77
2    c       88         88           88
3    d       99         99           99
4    e       66         66           66
5    f       55         55           55
6    g       77         77           77
7    h       99         99           99
8    i       33         33           33
9    r       88         88           88