In [10]:
import pandas as pd

In [11]:
import os

os.getcwd()

'C:\\Users\\hp\\Data Analysis\\EDA\\Pandas'

# Load CSV file

In [17]:
df_csv = pd.read_csv("Data/iris (1).csv") #loading iris.csv using pandas
df_csv

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# Load excel file

In [19]:
df_excel = pd.read_excel("Data/weather_data.xlsx") #loading iris.csv using pandas
df_excel

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [21]:
df_csv = pd.read_csv("Data/std_data1.csv")
df_csv

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

# usecols

In [55]:
df_csv = pd.read_csv("Data/std_data1.csv",usecols=["ENGLISH"]) #access rows
df_csv

   ENGLISH
0       67
1       87
2       66
3       56
4       89
5       88
6       90
7       79

In [56]:
df_csv = pd.read_csv("Data/std_data1.csv",usecols=[2]) #acess by index
df_csv

   ENGLISH
0       67
1       87
2       66
3       56
4       89
5       88
6       90
7       79

In [25]:
df_csv = pd.read_csv("Data/std_data1.csv",usecols=["ENGLISH","SCIENCE"])
df_csv

   ENGLISH  SCIENCE
0       67       66
1       87       65
2       66       63
3       56       66
4       89       56
5       88       89
6       90       88
7       79       90

# nrows

In [27]:
df_csv = pd.read_csv("Data/std_data1.csv",nrows=4)
df_csv

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66

# skiprows

In [30]:
pd.read_csv("Data/std_data2.csv",skiprows=1)

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [33]:
pd.read_csv("Data/std_data2.csv",skiprows=[2]) #it skips sencond index row

  ABC SCHOOL Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      SNAME    SCLASS     ENGLISH   COMPUTER    SCIENCE
1          B         12         87         56         65
2          C         11         66         89         63
3          D         10         56         88         66
4          E         10         89         90         56
5          F          9         88         85         89
6          G         12         90         83         88
7          H         11         79         88         90

In [34]:
pd.read_csv("Data/std_data2.csv",skiprows=2) #it skips first two rows

   A  10  67  66  66.1
0  B  12  87  56    65
1  C  11  66  89    63
2  D  10  56  88    66
3  E  10  89  90    56
4  F   9  88  85    89
5  G  12  90  83    88
6  H  11  79  88    90

In [36]:
pd.read_csv("Data/std_data1.csv",skiprows=[1,7,3]) #multiple index rows skips

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     B       12       87        56       65
1     D       10       56        88       66
2     E       10       89        90       56
3     F        9       88        85       89
4     H       11       79        88       90

# Header

In [39]:
pd.read_csv("Data/std_data_nocols.csv")

   A  10  67  66  66.1
0  B  12  87  56    65
1  C  11  66  89    63
2  D  10  56  88    66
3  E  10  89  90    56
4  F   9  88  85    89
5  G  12  90  83    88
6  H  11  79  88    90

In [37]:
pd.read_csv("Data/std_data_nocols.csv",header=None)

   0   1   2   3     4
0  A  10  67  66  66.1
1  B  12  87  56  65.0
2  C  11  66  89  63.0
3  D  10  56  88  66.0
4  E  10  89  90  56.0
5  F   9  88  85  89.0
6  G  12  90  83  88.0
7  H  11  79  88  90.0

# Name

In [40]:
pd.read_csv("Data/std_data_nocols.csv",header=None,names=["Name","cls","Eng","Sci","Comp"])

  Name  cls  Eng  Sci  Comp
0    A   10   67   66  66.1
1    B   12   87   56  65.0
2    C   11   66   89  63.0
3    D   10   56   88  66.0
4    E   10   89   90  56.0
5    F    9   88   85  89.0
6    G   12   90   83  88.0
7    H   11   79   88  90.0

# index_col

In [41]:
pd.read_csv("Data/std_data1.csv")

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [42]:
pd.read_csv("Data/std_data1.csv",index_col="SNAME")

       SCLASS   ENGLISH  COMPUTER  SCIENCE
SNAME
A           10       67        66       66
B           12       87        56       65
C           11       66        89       63
D           10       56        88       66
E           10       89        90       56
F            9       88        85       89
G           12       90        83       88
H           11       79        88       90

# parse_dates

In [45]:
df_date = pd.read_csv("Data/hyd.csv")
df_date

          Date  Temp
0   21-01-2022  30.0
1   22-01-2022  28.0
2   23-01-2022   NaN
3   24-01-2022  29.0
4   25-01-2022  31.0
5   26-01-2022  32.0
6   27-01-2022  34.0
7   28-01-2022   NaN
8   29-01-2022  36.0
9   30-01-2022  38.0
10  31-01-2022   NaN
11  13-02-2022  25.0
12  14-02-2022   NaN
13  15-02-2022  22.0
14  16-02-2022  21.0
15  17-02-2022   NaN
16  18-02-2022  22.0
17  19-02-2022   NaN
18  20-02-2022  20.0

In [47]:
df_date.dtypes

Date     object
Temp    float64
dtype: object

In [49]:
import warnings
warnings.filterwarnings("ignore")

In [51]:
df_date = pd.read_csv("Data/hyd.csv",parse_dates=["Date"])
df_date

         Date  Temp
0  2022-01-21  30.0
1  2022-01-22  28.0
2  2022-01-23   NaN
3  2022-01-24  29.0
4  2022-01-25  31.0
5  2022-01-26  32.0
6  2022-01-27  34.0
7  2022-01-28   NaN
8  2022-01-29  36.0
9  2022-01-30  38.0
10 2022-01-31   NaN
11 2022-02-13  25.0
12 2022-02-14   NaN
13 2022-02-15  22.0
14 2022-02-16  21.0
15 2022-02-17   NaN
16 2022-02-18  22.0
17 2022-02-19   NaN
18 2022-02-20  20.0

In [52]:
df_date.dtypes

Date    datetime64[ns]
Temp           float64
dtype: object

# Exporting csv and excel file

In [53]:
df_date.to_csv("exporting.csv")

In [54]:
df_date.to_excel("exporting.xlsx")