In [3]:
import pandas as pd

# Selection

In [4]:
df_iris = pd.read_csv("data/iris (1).csv")
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df_iris["Species"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [6]:
df_iris.Species #same as above

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [7]:
df_iris[["Species"]]

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [8]:
df_iris[["SepalLengthCm","Species"]] #multiple

     SepalLengthCm         Species
0              5.1     Iris-setosa
1              4.9     Iris-setosa
2              4.7     Iris-setosa
3              4.6     Iris-setosa
4              5.0     Iris-setosa
..             ...             ...
145            6.7  Iris-virginica
146            6.3  Iris-virginica
147            6.5  Iris-virginica
148            6.2  Iris-virginica
149            5.9  Iris-virginica

[150 rows x 2 columns]

## Position and Label Based Indexing: df.iloc and df.loc

In [9]:
df_iris.loc[:,"SepalLengthCm"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [10]:
df_iris.loc[:,"SepalLengthCm":"PetalLengthCm"]

     SepalLengthCm  SepalWidthCm  PetalLengthCm
0              5.1           3.5            1.4
1              4.9           3.0            1.4
2              4.7           3.2            1.3
3              4.6           3.1            1.5
4              5.0           3.6            1.4
..             ...           ...            ...
145            6.7           3.0            5.2
146            6.3           2.5            5.0
147            6.5           3.0            5.2
148            6.2           3.4            5.4
149            5.9           3.0            5.1

[150 rows x 3 columns]

In [11]:
df_iris.loc[:,["SepalLengthCm","PetalLengthCm"]]

     SepalLengthCm  PetalLengthCm
0              5.1            1.4
1              4.9            1.4
2              4.7            1.3
3              4.6            1.5
4              5.0            1.4
..             ...            ...
145            6.7            5.2
146            6.3            5.0
147            6.5            5.2
148            6.2            5.4
149            5.9            5.1

[150 rows x 2 columns]

# Selecting a single using iloc

In [12]:
df_iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [13]:
df_iris.iloc[:,5]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [14]:
df_iris.iloc[:,2:5]

     SepalWidthCm  PetalLengthCm  PetalWidthCm
0             3.5            1.4           0.2
1             3.0            1.4           0.2
2             3.2            1.3           0.2
3             3.1            1.5           0.2
4             3.6            1.4           0.2
..            ...            ...           ...
145           3.0            5.2           2.3
146           2.5            5.0           1.9
147           3.0            5.2           2.0
148           3.4            5.4           2.3
149           3.0            5.1           1.8

[150 rows x 3 columns]

In [15]:
df_iris.iloc[:,[2,5,3]]

     SepalWidthCm         Species  PetalLengthCm
0             3.5     Iris-setosa            1.4
1             3.0     Iris-setosa            1.4
2             3.2     Iris-setosa            1.3
3             3.1     Iris-setosa            1.5
4             3.6     Iris-setosa            1.4
..            ...             ...            ...
145           3.0  Iris-virginica            5.2
146           2.5  Iris-virginica            5.0
147           3.0  Iris-virginica            5.2
148           3.4  Iris-virginica            5.4
149           3.0  Iris-virginica            5.1

[150 rows x 3 columns]

# Slicing

In [16]:
df_iris.iloc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [17]:
df_iris.iloc[[0]]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa

In [18]:
df_iris.iloc[[2,4,6,7,100]] #multiple

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
2,3,4.7,3.2,1.3,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
100,101,6.3,3.3,6.0,2.5,Iris-virginica

In [19]:
df_iris.iloc[[-2,-4,-6,-7,-100]] #last few

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
50,51,7.0,3.2,4.7,1.4,Iris-versicolor

# Indexing

In [20]:
df_iris.iloc[0,0]

np.int64(1)

In [21]:
df_iris.loc[0,"Species"] #using .loc

'Iris-setosa'

In [22]:
# selcting rows and columns
df_iris.iloc[[23,54,66,8],[1,2,3]]

    SepalLengthCm  SepalWidthCm  PetalLengthCm
23            5.1           3.3            1.7
54            6.5           2.8            4.6
66            5.6           3.0            4.5
8             4.4           2.9            1.4

In [23]:
#using lock
df_iris.loc[[23,54,66,8],["SepalLengthCm", "SepalWidthCm", "PetalLengthCm"]]

    SepalLengthCm  SepalWidthCm  PetalLengthCm
23            5.1           3.3            1.7
54            6.5           2.8            4.6
66            5.6           3.0            4.5
8             4.4           2.9            1.4

In [24]:
df_iris.iloc[0:7,1:4]

   SepalLengthCm  SepalWidthCm  PetalLengthCm
0            5.1           3.5            1.4
1            4.9           3.0            1.4
2            4.7           3.2            1.3
3            4.6           3.1            1.5
4            5.0           3.6            1.4
5            5.4           3.9            1.7
6            4.6           3.4            1.4

In [25]:
df_iris.loc[0:7,"SepalLengthCm":"PetalLengthCm"]

   SepalLengthCm  SepalWidthCm  PetalLengthCm
0            5.1           3.5            1.4
1            4.9           3.0            1.4
2            4.7           3.2            1.3
3            4.6           3.1            1.5
4            5.0           3.6            1.4
5            5.4           3.9            1.7
6            4.6           3.4            1.4
7            5.0           3.4            1.5

# Filtering

In [26]:
df_iris["SepalLengthCm"] > 5

0       True
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: SepalLengthCm, Length: 150, dtype: bool

In [27]:
df_iris[df_iris["SepalLengthCm"] > 5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [28]:
df_iris.loc[df_iris["SepalLengthCm"] > 5, "Species"]

0         Iris-setosa
5         Iris-setosa
10        Iris-setosa
14        Iris-setosa
15        Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 118, dtype: object

# Based on two criteria with Operator

In [29]:
df_iris[(df_iris["SepalLengthCm"] > 5) & (df_iris["SepalLengthCm"] < 6)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
44,45,5.1,3.8,1.9,0.4,Iris-setosa
46,47,5.1,3.8,1.6,0.2,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
89,90,5.5,2.5,4.0,1.3,Iris-versicolor
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
94,95,5.6,2.7,4.2,1.3,Iris-versicolor
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor
101,102,5.8,2.7,5.1,1.9,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [30]:
df_iris[df_iris["SepalLengthCm"].between(5,6)] #same as above

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
119,120,6.0,2.2,5.0,1.5,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [31]:
df_iris[(df_iris["SepalLengthCm"] > 5) | (df_iris["SepalLengthCm"] < 6)] #with or operator

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# filtering based on  min and max values

In [32]:
df_iris["SepalLengthCm"].idxmax()

131

In [33]:
df_iris.iloc[131]

Id                          132
SepalLengthCm               7.9
SepalWidthCm                3.8
PetalLengthCm               6.4
PetalWidthCm                2.0
Species          Iris-virginica
Name: 131, dtype: object

In [34]:
df_iris.loc[131,"Species"]

'Iris-virginica'

In [40]:
df_iris[df_iris["Species"] == "Iris-virginica"]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [35]:
df_iris["SepalLengthCm"].idxmin()

13

In [36]:
df_iris.iloc[13]

Id                        14
SepalLengthCm            4.3
SepalWidthCm             3.0
PetalLengthCm            1.1
PetalWidthCm             0.1
Species          Iris-setosa
Name: 13, dtype: object

In [41]:
df_iris.loc[13,"Species"]

'Iris-setosa'

In [37]:
df_iris["SepalLengthCm"].min(),df_iris["SepalLengthCm"].idxmin()

(4.3, 13)

In [38]:
df_iris["SepalLengthCm"].max(),df_iris["SepalLengthCm"].idxmax()

(7.9, 131)