# Q.1) Create a Pandas DataFrame with the following data:
large_dict = {'ID': np.arange(1, 100001),
'Name': [f'Person_{i}' for i in range(1, 100001)],
'Age': np.random.randint(18, 65, size=100000)
'Salary': np.random.randint(40000, 120000, size=100000)
'City': np.random.choice(['New York', 'London', 'Tokyo', 'Paris'], size=100000)}
Convert the dataframe into both CSV & Excel files and read those files.

In [69]:
import pandas as pd
import numpy as np
#Pandas DataFrame
large_dict = {'ID': np.arange(1, 100001),
              'Name': [f'Person_{i}' for i in range(1, 100001)],
              'Age': np.random.randint(18, 65, size=100000),
              'Salary': np.random.randint(40000, 120000, size=100000),
              'City': np.random.choice(['New York', 'London', 'Tokyo', 'Paris'], size=100000)}

df = pd.DataFrame(large_dict)
df

           ID           Name  Age  Salary      City
0           1       Person_1   23   41176     Paris
1           2       Person_2   22   43441     Paris
2           3       Person_3   57   96200     Paris
3           4       Person_4   30   41786  New York
4           5       Person_5   22   67291    London
...       ...            ...  ...     ...       ...
99995   99996   Person_99996   59   79670    London
99996   99997   Person_99997   47   75323     Tokyo
99997   99998   Person_99998   34  110494     Paris
99998   99999   Person_99999   49  104634    London
99999  100000  Person_100000   41   89820     Tokyo

[100000 rows x 5 columns]

In [70]:
#convert to csv
df.to_csv("large_dict.csv",index = False)

In [71]:
#covert to excel
df.to_excel("large_dict.xlsx",index = False)

In [72]:
#read csv
pd.read_csv("large_dict.csv")

           ID           Name  Age  Salary      City
0           1       Person_1   23   41176     Paris
1           2       Person_2   22   43441     Paris
2           3       Person_3   57   96200     Paris
3           4       Person_4   30   41786  New York
4           5       Person_5   22   67291    London
...       ...            ...  ...     ...       ...
99995   99996   Person_99996   59   79670    London
99996   99997   Person_99997   47   75323     Tokyo
99997   99998   Person_99998   34  110494     Paris
99998   99999   Person_99999   49  104634    London
99999  100000  Person_100000   41   89820     Tokyo

[100000 rows x 5 columns]

In [73]:
#eard ecxel
pd.read_excel("large_dict.xlsx")

           ID           Name  Age  Salary      City
0           1       Person_1   23   41176     Paris
1           2       Person_2   22   43441     Paris
2           3       Person_3   57   96200     Paris
3           4       Person_4   30   41786  New York
4           5       Person_5   22   67291    London
...       ...            ...  ...     ...       ...
99995   99996   Person_99996   59   79670    London
99996   99997   Person_99997   47   75323     Tokyo
99997   99998   Person_99998   34  110494     Paris
99998   99999   Person_99999   49  104634    London
99999  100000  Person_100000   41   89820     Tokyo

[100000 rows x 5 columns]

##
----

# Q.1) Display information about the DataFrame. And show the last ten rows of the dataframe.
* Get statistical information about the numeric columns from the above dataframe.

In [52]:
#original data
df

           ID           Name  Age  Salary      City
0           1       Person_1   25   57984     Tokyo
1           2       Person_2   35   54913     Tokyo
2           3       Person_3   31   86162  New York
3           4       Person_4   20   53999    London
4           5       Person_5   29   48542    London
...       ...            ...  ...     ...       ...
99995   99996   Person_99996   60  112288  New York
99996   99997   Person_99997   60   64711  New York
99997   99998   Person_99998   59   96782     Paris
99998   99999   Person_99999   31  104415     Paris
99999  100000  Person_100000   38  107889     Tokyo

[100000 rows x 5 columns]

In [53]:
#information about DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      100000 non-null  int64
 1   Name    100000 non-null  object
 2   Age     100000 non-null  int32
 3   Salary  100000 non-null  int32
 4   City    100000 non-null  object
dtypes: int32(2), int64(1), object(2)
memory usage: 3.1+ MB

In [56]:
#display last 10 rows
df.tail(10)

           ID           Name  Age  Salary      City
99990   99991   Person_99991   26   94917  New York
99991   99992   Person_99992   30   41472  New York
99992   99993   Person_99993   25  111149    London
99993   99994   Person_99994   58   95783     Paris
99994   99995   Person_99995   48   96685     Tokyo
99995   99996   Person_99996   60  112288  New York
99996   99997   Person_99997   60   64711  New York
99997   99998   Person_99998   59   96782     Paris
99998   99999   Person_99999   31  104415     Paris
99999  100000  Person_100000   38  107889     Tokyo

In [58]:
#columns of numeric values and theries statistical information
df1 = df.describe()
df1

                  ID            Age         Salary
count  100000.000000  100000.000000  100000.000000
mean    50000.500000      41.008980   80122.253420
std     28867.657797      13.552478   23092.847057
min         1.000000      18.000000   40000.000000
25%     25000.750000      29.000000   60059.000000
50%     50000.500000      41.000000   80201.000000
75%     75000.250000      53.000000  100121.000000
max    100000.000000      64.000000  119999.000000

##
----

# Q.3) Create a Pandas DataFrame with columns 'City', 'Temperature', and 'Humidity' containing the following data:
| City        | Temperature | Humidity |
|-------------|-------------|----------|
| New York    | 75          | 60       |
| Chicago     | 68          | 55       |
| Los Angeles | 85          | 45       |
| Miami       | 80          | 70       |
* Display the rows where the Temperature is above 70.
* Display the rows where the Humidity is below 60.
* Display city with temperature 68 and humidity 55.

In [60]:
#Pandas DataFrame with columns 'City', 'Temperature', and 'Humidity' containing the above data
data = {"City":["New York","Chicago","Los Angeles","Miami"],
        "Temperature":[75,68,85,80],
        "Humidity":[60,55,45,70]}

df = pd.DataFrame(data)
df

          City  Temperature  Humidity
0     New York           75        60
1      Chicago           68        55
2  Los Angeles           85        45
3        Miami           80        70

In [67]:
#Display the rows where the Temperature is above 70.
print(df[df["Temperature"] > 70])

          City  Temperature  Humidity
0     New York           75        60
2  Los Angeles           85        45
3        Miami           80        70

In [68]:
# Display the rows where the Humidity is below 60.
print(df[df["Humidity"] < 70])

          City  Temperature  Humidity
0     New York           75        60
1      Chicago           68        55
2  Los Angeles           85        45

In [66]:
#Display city with temperature 68 and humidity 55.
print(df[(df['Temperature'] == 68) & (df['Humidity'] == 55)])

      City  Temperature  Humidity
1  Chicago           68        55

##
-----