# Q.1) Create a Pandas DataFrame with the following data:
	data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        		  'Age': [25, 30, 35, 40],
        		 'Salary': [50000, 60000, 75000, 90000]}
* Print the 'Name' column from the above dataframe. Also Print the first two rows of the DataFrame.

In [2]:
import pandas as pd
#creating dataframe 
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        		  'Age': [25, 30, 35, 40],
        		 'Salary': [50000, 60000, 75000, 90000]
       }
df = pd.DataFrame(data)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   90000

In [6]:
#printing name column
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [7]:
#first two rows
df.head(2)

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000

##
-------

# Q.2) Print the details of the person with the highest and lowest salary from the above dataframe.
* Calculate and print the average age and salary.
* Select and print the rows where Age is less than 35 and Salary is greater than 60000.

In [9]:
#printit highest and lowest salary
df = pd.DataFrame(data)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   90000

In [11]:
#printing highest and lowest salary
highest_salary = df[df['Salary'] == df['Salary'].max()]
highest_salary

    Name  Age  Salary
3  David   40   90000

In [12]:
lowest_salary = df[df['Salary'] == df['Salary'].min()]
lowest_salary

    Name  Age  Salary
0  Alice   25   50000

In [3]:
#avg age
avg_age = df['Age'].mean()
print(avg_age)

32.5

In [4]:
#avg Salary
avg_salary = df['Salary'].mean()
print(avg_salary)

68750.0

In [16]:
#printing the rows where Age is less than 35 and Salary is greater than 60000.
n_rows = df[(df['Age'] < 35) & (df['Salary'] > 60000)]
n_rows

Empty DataFrame
Columns: [Name, Age, Salary]
Index: []

##
------

# Q.3) Create a Pandas DataFrame from the following dictionary:
 	data = {'City': ['New York', 'London', 'Tokyo', 'Paris'],
 'Population': [8398748, 8982256, 37435191, 2140526],
 'Area_km2': [468.9, 1572, 2191, 105.4]}
* Add a new column 'Population_Density' calculated as Population/Area_km2.  Print the modified DataFrame.

In [3]:
#creating Pandas DataFrame
import pandas as pd
data = {'City': ['New York', 'London', 'Tokyo', 'Paris'],
 'Population': [8398748, 8982256, 37435191, 2140526],
 'Area_km2': [468.9, 1572, 2191, 105.4]}


df = pd.DataFrame(data)
df

       City  Population  Area_km2
0  New York     8398748     468.9
1    London     8982256    1572.0
2     Tokyo    37435191    2191.0
3     Paris     2140526     105.4

In [4]:
#Add a new column 'Population_Density' calculated as Population/Area_km2. Print the modified DataFrame
df['Population_Density'] = df['Population'] / df['Area_km2']
df

       City  Population  Area_km2  Population_Density
0  New York     8398748     468.9        17911.597356
1    London     8982256    1572.0         5713.903308
2     Tokyo    37435191    2191.0        17085.892743
3     Paris     2140526     105.4        20308.595825

##
----