# Q.1) You have a DataFrame student_data with columns 'StudentID', 'Name', 'Age', and 'Grade'. It contains missing values.
data = {'StudentID': [1, 2, 3, 4, 5],
'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Age': [25, 22, None, 28, 30],
'Grade': [85, 92, 78, None, 95]}
* Perform the following tasks:
    * Display the count of missing values in each column.
    * Fill missing values in the 'Age' column with the mean age.
    * Remove rows with missing values in any column.

In [25]:
import pandas as pd
#dataframe
data = {'StudentID': [1, 2, 3, 4, 5],
'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Age': [25, 22, None, 28, 30],
'Grade': [85, 92, 78, None, 95]}

df = pd.DataFrame(data)
df

   StudentID     Name   Age  Grade
0          1    Alice  25.0   85.0
1          2      Bob  22.0   92.0
2          3  Charlie   NaN   78.0
3          4    David  28.0    NaN
4          5      Eva  30.0   95.0

In [26]:
# Display the count of missing values in each column.
df.isna().sum()

StudentID    0
Name         0
Age          1
Grade        1
dtype: int64

In [27]:
# Fill missing values in the 'Age' column with the mean age.
df["Age"].fillna(df["Age"].mean())

0    25.00
1    22.00
2    26.25
3    28.00
4    30.00
Name: Age, dtype: float64

In [28]:
# Remove rows with missing values in any column
df.dropna()

   StudentID   Name   Age  Grade
0          1  Alice  25.0   85.0
1          2    Bob  22.0   92.0
4          5    Eva  30.0   95.0

##
----

# Q.2) You have a DataFrame employee_data with columns 'EmployeeID', 'Department', and 'Salary'. Some 'Department' values are missing.
data = {'EmployeeID': [101, 102, 103, 104, 105],
'Department': ['HR', 'IT', None, 'IT', 'HR'],
'Salary': [60000, 75000, 55000, 80000, 65000]}
* Perform the following tasks:
    * Display the count of missing values in the 'Department' column.
    * Impute missing 'Department' values with the most frequent department.

In [45]:
#DataFrame
data = {'EmployeeID': [101, 102, 103, 104, 105],
'Department': ['HR', 'IT', None, 'IT', 'HR'],
'Salary': [60000, 75000, 55000, 80000, 65000]}

df1 = pd.DataFrame(data)
df1

   EmployeeID Department  Salary
0         101         HR   60000
1         102         IT   75000
2         103       None   55000
3         104         IT   80000
4         105         HR   65000

In [46]:
# Display the count of missing values in the 'Department' column.
print(df1["Department"].isna().sum())

1

In [47]:
# Impute missing 'Department' values with the most frequent department.
df1["Department"].mode()[0]

'HR'

In [49]:
df1.columns

Index(['EmployeeID', 'Department', 'Salary'], dtype='object')

In [51]:
df1["Department"].fillna(df1["Department"].mode()[0])
df1

   EmployeeID Department  Salary
0         101         HR   60000
1         102         IT   75000
2         103       None   55000
3         104         IT   80000
4         105         HR   65000

##
----

# Q.3)  You have a DataFrame stock_prices with columns 'Date' and 'Closing_Price'. It represents daily stock prices.
data = {'Date': ['2022-01-01', '2022-01-02', '2022-01-04', '2022-01-05'],
'Closing_Price': [100, None, 120, None]}
* Perform the following tasks:
    * Display the count of missing values in the 'Closing_Price' column.
    * Fill missing 'Closing_Price' values using forward fill method for time series data.

In [33]:
#DataFrame
data = {'Date': ['2022-01-01', '2022-01-02', '2022-01-04', '2022-01-05'],
         'Closing_Price': [100, None, 120, None]}

df2 = pd.DataFrame(data)
df2

         Date  Closing_Price
0  2022-01-01          100.0
1  2022-01-02            NaN
2  2022-01-04          120.0
3  2022-01-05            NaN

In [34]:
# Display the count of missing values in the 'Closing_Price' column.
print(df2["Closing_Price"].isna().sum())

2

In [35]:
# Fill missing 'Closing_Price' values using forward fill method for time series data.
df2.fillna(method = "ffill")

C:\Users\hp\AppData\Local\Temp\ipykernel_21552\4199867806.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method = "ffill")

         Date  Closing_Price
0  2022-01-01          100.0
1  2022-01-02          100.0
2  2022-01-04          120.0
3  2022-01-05          120.0

##
----