# Q.1) Suppose you have two Pandas DataFrames, df1 and df2, with a common column 'ID'. Perform an inner join on these DataFrames and display the result.
* df1 = ['ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']} df2 = {'ID': [2, 3, 4], 'Age': [25, 30, 22]}

In [1]:
import pandas as pd

In [10]:
# Perform an inner join on these DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']}) 
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Age': [25, 30, 22]})

display(df1,df2)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

   ID  Age
0   2   25
1   3   30
2   4   22

In [17]:
pd.merge(df1, df2,how = "inner")

   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30

##
-------------

# Q.2) Given two DataFrames, left_df and right_df, perform a left join and display the result.
* left_df = {'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']}
* right_df = {'ID': [2, 3, 4], 'Age': [25, 30, 22]}

In [12]:
# left join and display the result.¶
left_df = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
right_df = pd.DataFrame({'ID': [2, 3, 4], 'Age': [25, 30, 22]})
display(left_df,right_df)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

   ID  Age
0   2   25
1   3   30
2   4   22

In [15]:
pd.merge(left_df, right_df,how = "left")

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0

##
------

# Q.3) Create two DataFrames, df7 and df8, and perform a cross join. Display the result.
* df7 = {'Color': ['Red', 'Green', 'Blue']} df8 = {'Size': ['Small', 'Medium', 'Large']}

In [14]:
# cross join
df7 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue']})
df8 = pd.DataFrame({'Size': ['Small', 'Medium', 'Large']})
display(df7,df8)

   Color
0    Red
1  Green
2   Blue

     Size
0   Small
1  Medium
2   Large

In [18]:
pd.merge(df7, df8,how = "cross")

   Color    Size
0    Red   Small
1    Red  Medium
2    Red   Large
3  Green   Small
4  Green  Medium
5  Green   Large
6   Blue   Small
7   Blue  Medium
8   Blue   Large

##
----

# Q.4) Create two DataFrames, df3 and df4, and perform an outer join. Display the result.
* df3 = {'ID': [1, 2, 3], 'City': ['New York', 'San Francisco', 'Los Angeles']} df4 = ['ID': [2, 3, 4], 'Population': [8500000, 880000, 4000000]}

In [19]:
# outer join
df3 = pd.DataFrame({'ID': [1, 2, 3], 'City': ['New York', 'San Francisco', 'Los Angeles']}) 
df4 = pd.DataFrame({'ID': [2, 3, 4], 'Population': [8500000, 880000, 4000000]})
display(df3,df4)

   ID           City
0   1       New York
1   2  San Francisco
2   3    Los Angeles

   ID  Population
0   2     8500000
1   3      880000
2   4     4000000

In [23]:
pd.merge(df3, df4,how = "outer")

   ID           City  Population
0   1       New York         NaN
1   2  San Francisco   8500000.0
2   3    Los Angeles    880000.0
3   4            NaN   4000000.0

##
-----

# Q.5) Given two DataFrames, df5 and df6, perform a right join and display the result.
* df5 = ['ID': [1, 2, 3], 'Product': ['Laptop', 'Mouse', 'Keyboard']} df6 = {'ID': [2, 3, 4], 'Price': [1200, 30, 50]}

In [21]:
# right join
df5 = pd.DataFrame({'ID': [1, 2, 3], 'Product': ['Laptop', 'Mouse', 'Keyboard']})
df6 = pd.DataFrame({'ID': [2, 3, 4], 'Price': [1200, 30, 50]})
display(df5,df6)

   ID   Product
0   1    Laptop
1   2     Mouse
2   3  Keyboard

   ID  Price
0   2   1200
1   3     30
2   4     50

In [22]:
pd.merge(df5, df6,how = "right")

   ID   Product  Price
0   2     Mouse   1200
1   3  Keyboard     30
2   4       NaN     50